CREATE TABLE CUSTOMER (
    NAME        VARCHAR(100)    NOT NULL,
    EMAIL       VARCHAR(100)    NOT NULL,
    PASSWD_HASH VARCHAR(100)    NOT NULL,
    PRIMARY KEY (EMAIL)
);

CREATE TABLE BUSINESS (
    NAME        VARCHAR(100)    NOT NULL,
    EMAIL       VARCHAR(100)    NOT NULL,
    PASSWD_HASH VARCHAR(100)    NOT NULL,
    PRIMARY KEY (EMAIL)
);

CREATE TABLE REVIEWS (
    CUSTOMER_EMAIL  VARCHAR(100)    NOT NULL,
    BUSINESS_EMAIL  VARCHAR(100)    NOT NULL,
    RATING          INT             NOT NULL,
    TEXT            VARCHAR(500)    NOT NULL,
    TIME            DATETIME,
    FOREIGN KEY (CUSTOMER_EMAIL) REFERENCES CUSTOMER(EMAIL),
    FOREIGN KEY (BUSINESS_EMAIL) REFERENCES BUSINESS(EMAIL)
);

CREATE TABLE POST (
    CUSTOMER_EMAIL  VARCHAR(100)    NOT NULL,
    TIME            DATETIME        NOT NULL,
    TEXT            VARCHAR(500)    NOT NULL,
    FOREIGN KEY (CUSTOMER_EMAIL) REFERENCES CUSTOMER(EMAIL)
);
